// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    //databaseURL:"https://smart-change-app-75006.firebaseio.com",
    apiKey: 'AIzaSyAp2Vi468g9-4kUUfU95N9kBUpx6w_yIyI',
    appId: '1:1075642509518:web:bce6a4d6aee023351c089f',
    messagingSenderId: '1075642509518',
    projectId: 'smart-change-app-75006',
    authDomain: 'smart-change-app-75006.firebaseapp.com',
    storageBucket: 'smart-change-app-75006.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    //databaseURL:"https://smart-change-app-75006.firebaseio.com",
    apiKey: 'AIzaSyBqKMF5vBPdexvVOpC4XKLocR3LybihBWs',
    appId: '1:1075642509518:android:8fa8aee2e23078951c089f',
    messagingSenderId: '1075642509518',
    projectId: 'smart-change-app-75006',
    storageBucket: 'smart-change-app-75006.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    //databaseURL:"https://smart-change-app-75006.firebaseio.com",
    apiKey: 'AIzaSyA8weO7U9i_ye-JLQ05m6PJxHgPWBJVHzs',
    appId: '1:1075642509518:ios:2ac8507cd326393c1c089f',
    messagingSenderId: '1075642509518',
    projectId: 'smart-change-app-75006',
    storageBucket: 'smart-change-app-75006.appspot.com',
    iosClientId: '1075642509518-ck7vjr4cgvgfg3q461t151drho7m48hj.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartChange',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    //databaseURL:"https://smart-change-app-75006.firebaseio.com",
    apiKey: 'AIzaSyA8weO7U9i_ye-JLQ05m6PJxHgPWBJVHzs',
    appId: '1:1075642509518:ios:d9598fc0eb5703cc1c089f',
    messagingSenderId: '1075642509518',
    projectId: 'smart-change-app-75006',
    storageBucket: 'smart-change-app-75006.appspot.com',
    iosClientId: '1075642509518-7nkveokb4u9dbgufhjck308t5caulsnj.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartChange.RunnerTests',
  );
}
